# Generated by Django 3.1.3 on 2020-11-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('isBlocked', models.BooleanField(db_column='is_blocked', default=False)),
                ('blockedByVehicleId', models.IntegerField(blank=True, db_column='blocked_by_vehicle_id', null=True)),
                ('createdAt', models.DateTimeField(db_column='created_at')),
                ('updatedAt', models.DateTimeField(db_column='updated_at')),
                ('isDeleted', models.BooleanField(db_column='is_deleted', default=False)),
            ],
            options={
                'db_table': 'parking_slot',
            },
        ),
    ]
