# Generated by Django 3.1.3 on 2020-11-04 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslots',
            name='createdAt',
            field=models.DateTimeField(db_column='created_at', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parkingslots',
            name='updatedAt',
            field=models.DateTimeField(db_column='updated_at', default=django.utils.timezone.now),
        ),
    ]
